use_frameworks!

platform :ios, '9.0'

target 'CKContainermodule_Example' do
  pod 'CKContainermodule', :path => '../'

  target 'CKContainermodule_Tests' do
    inherit! :search_paths

    
  end
end
